FROM python:3.12-slim-bookworm

# set work directory
WORKDIR /agentworld

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Packages
RUN apt-get -y update

# Dependencies
RUN pip install --upgrade pip
COPY ./docker/requirements.celery.txt .
RUN pip install -r requirements.celery.txt
# RUN playwright install
# RUN playwright install-deps

# Project copy
COPY ./core /agentworld/core