# Generated by Django 5.1.4 on 2024-12-15 10:56

import django.db.models.deletion
import imagekit.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('icon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='skill_icons/')),
                ('openapi_schema', models.TextField()),
                ('guidelines', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, choices=[('AnalyticsAutomation', 'Analytics Automation'), ('ConversationManagement', 'Conversation Management'), ('CRM', 'CRM'), ('DataEnrichment', 'Data & Enrichment'), ('IssueTracking', 'Issue Tracking & Ticketing'), ('LeadCapture', 'Lead Capture'), ('MarketingAutomation', 'Marketing Automation'), ('PhoneVideo', 'Phone & Video'), ('Scheduling', 'Scheduling'), ('ScreenCapture', 'Screen Capture'), ('SocialMedia', 'Social Media'), ('SurveysFeedback', 'Surveys & Feedback')], max_length=50, null=True)),
                ('auth_header', models.CharField(blank=True, default='', max_length=40)),
                ('auth_prefix', models.CharField(blank=True, default='', max_length=40)),
                ('auth_headers', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('openapi_schema', models.TextField()),
                ('guidelines', models.JSONField(blank=True, default=list)),
                ('auth_header', models.CharField(blank=True, default='', max_length=40)),
                ('auth_prefix', models.CharField(blank=True, default='', max_length=40)),
                ('auth_headers', models.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.skilltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='agents.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.token'),
        ),
    ]
