# Generated by Django 5.1.4 on 2024-12-10 17:17

import apps.agents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenconfig',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('openapi_schema', models.TextField()),
                ('guidelines', models.JSONField(blank=True, default=list)),
                ('token_config', models.ForeignKey(blank=True, default=apps.agents.models.createTokenConfig, null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.tokenconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('openapi_schema', models.TextField()),
                ('guidelines', models.JSONField(blank=True, default=list)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.token')),
                ('token_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.tokenconfig')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.skill')),
            ],
        ),
    ]
